### ISSUE TITLE
Evaluate adding vat.live checks on pools and plans

### ISSUE THREAD

**Issue by gbalabasquer** [makerdao/dss-direct-deposit#55]
We should define if we will rely on the esm.denyProxy or we can build something that makes the contract to secure themselves after Global Shutdown.

**Comment by hexonaut** [comment]
Not sure I understand. `esm.denyProxy` is used to deny governance in an attack scenario. That's not the same as checking if Global Shutdown has been triggered.

**Comment by gbalabasquer** [comment]
Closing this as it was already solved adding the `vat.live` check and having a special `onlyHub` modifier.
